FROM golang:1.25

# Install Delve (debugger) and Reflex (file watcher)
RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
    go install github.com/cespare/reflex@latest

WORKDIR /workspace

# Set cache env vars to ensuring they are targeted by our volume mounts
ENV GOCACHE=/go/.cache/go-build
ENV GOMODCACHE=/go/pkg/mod
# Expose ports
EXPOSE 5758 2345

# The default command will be overridden by the script, but we can set a safe default
CMD ["bash"]
